### ISSUE TITLE
Add More Functionality To Listing Page

### ISSUE THREAD

**Issue by CjKhaled** [CjKhaled/roost-frontend#10]
When on the listings page, a user should be able to do more.

Tasks

- [x] The message button should send them to the messages screen, where they could then send a message to the lister
- [x] Under Lister on the top right hand card, instead of showing User, it should show the listers first and last name
- [x] When clicking save, it should be saved to the listers favorited listings in local storage

**Comment by Tiger9406** [comment]
I got this
